<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class SekolahSeeder extends Seeder
{
    public function run()
    {
        $faker = \Faker\Factory::create('id_ID');

        // for ($i = 0; $i < 50; $i++) {
        //     $jenis = rand(0, 1) ? 'SMA' : 'SMK';
        //     $angka = mt_rand(1, 20);
        //     $kecamatan = $faker->city;
        //     $sekolah = $jenis . ' ' . $angka . ' ' . $kecamatan;
        //     $data = [
        //         'user_id' => $i + 2,
        //         'nama' => $sekolah,
        //         'slug' => url_title($sekolah, '-', true),
        //         'kecamatan' => $kecamatan,
        //         'alamat'    => $faker->address,
        //         'kepsek'    => $faker->userName,
        //         'email'    => $faker->safeEmail,
        //         'nohp'    => $faker->phoneNumber,
        //         'status'    => rand(0, 1) ? 'Negeri' : 'Swasta',
        //         'latitude'    => mt_rand(10823, 10847) / 100,
        //         'longitude'    => mt_rand(647, 712) / 100 * -1,
        //         'created_at'    => Time::createFromTimestamp($faker->unixTime),
        //         'updated_at'    => Time::now(),
        //     ];
        //     // Using Query Builder
        //     $this->db->table('sekolah')->insert($data);
        // }
        $sekolah = [
            [
                "id" => 20212958,
                "user_id" => 2,
                "nama" => "SMA Negeri 1 Mandirancan",
                "slug" => "smanegeri1mandirancan",
                "status" => "Negeri",
                "latitude" => "108.4730647",
                "longitude" => "-6.815974381",
                "kecamatan" => "Mandirancan",
                "alamat" => "Jl. Siliwangi No.I A, Mandirancan, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Agus Hilman",
                "email" => "sma1mandirancan@gmail.com",
                "nohp" => "0231613026",
                "akreditasi" => "A",
                "guru" => 60,
                "siswa_laki" => 427,
                "siswa_perempuan" => 732,
                "kurikulum" => "SMA 2013 Bhs&Budaya",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 25,
                "laboratorium" => 1,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20246367,
                "user_id" => 3,
                "nama" => "SMA Negeri 1 Pasawahan",
                "slug" => "smanegeri1pasawahan",
                "status" => "Negeri",
                "latitude" => "108.4343985", 
                "longitude" => "-6.808562390",
                "kecamatan" => "Pasawahan",
                "alamat" => "Jl. CireaPasawahan, Singkup, Kec. Pasawahan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Ipit Rahmiati",
                "email" => "sman1pasawahan@gmail.com",
                "nohp" => "02318306097",
                "akreditasi" => "A",
                "guru" => 26,
                "siswa_laki" => 246,
                "siswa_perempuan" => 210,
                "kurikulum" => "SMA 2013 Bhs&Budaya",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 19,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212937,
                "user_id" => 4,
                "nama" => "SMA Negeri 1 Cilimus",
                "slug" => "smanegeri1cilimus",
                "status" => "Negeri",
                "latitude" => "108.4983167",
                "longitude" => "-6.874895464",
                "kecamatan" => "Cilimus",
                "alamat" => "Caracas, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Nono Sudrono",
                "email" => "smkn_1cilimus@yahoo.com ",
                "nohp" => "02318910145",
                "akreditasi" => "A",
                "guru" => 67,
                "siswa_laki" => 399,
                "siswa_perempuan" => 883,
                "kurikulum" => "SMA 2013 IPS",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 36,
                "laboratorium" => 3,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212963,
                "user_id" => 5,
                "nama" => "SMA Negeri 1 Jalaksana",
                "slug" => "smanegeri1jalaksana",
                "status" => "Negeri",
                "latitude" => "108.4909223",
                "longitude" => "-6.917618380",
                "kecamatan" => "Jalaksana",
                "alamat" => "Jl. Raya Padamenak, Jalaksana, 45554, Padamenak, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Nanang Warsa",
                "email" => "sman1jlksn.ops@gmail.com",
                "nohp" => "0231874407",
                "akreditasi" => "A",
                "guru" => 65,
                "siswa_laki" => 363,
                "siswa_perempuan" => 890,
                "kurikulum" => "SMA 2013 IPS",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 34,
                "laboratorium" => 4,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212962,
                "user_id" => 6,
                "nama" => "SMA Negeri 1 Kadugede",
                "slug" => "smanegeri1kadugede",
                "status" => "Negeri",
                "latitude" => "108.4506389",
                "longitude" => "-7.004580627",
                "kecamatan" => "Kadugede",
                "alamat" => "Jl. Syech Manglayang No.65, Babatan, Kec. Kadugede, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Rhida Jaya Bhuana",
                "email" => "smansaka@ymail.com",
                "nohp" => "0231872816",
                "akreditasi" => "A",
                "guru" => 52,
                "siswa_laki" => 325,
                "siswa_perempuan" => 734,
                "kurikulum" => "SMA 2013 MIPA",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 30,
                "laboratorium" => 3,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212938,
                "user_id" => 7,
                "nama" => "SMA Negeri 1 Cigugur",
                "slug" => "smanegeri1cigugur",
                "status" => "Negeri",
                "latitude" => "108.4626764",
                "longitude" => "-6.983603008",
                "kecamatan" => "Cigugur",
                "alamat" => "Jl. Sukamulya No.12, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Nono Sudarsono",
                "email" => "sman1cggr@gmail.com",
                "nohp" => "0231873840",
                "akreditasi" => "A",
                "guru" => 41,
                "siswa_laki" => 377,
                "siswa_perempuan" => 494,
                "kurikulum" => "SMA 2013 MIPA",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 28,
                "laboratorium" => 4,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212939,
                "user_id" => 8,
                "nama" => "SMA Negeri 1 Ciawigebang",
                "slug" => "smanegeri1ciawigebang",
                "status" => "Negeri",
                "latitude" => "108.5889720",
                "longitude" => "-6.974219007",
                "kecamatan" => "Ciawigebang",
                "alamat" => "Jl. Raya Siliwangi No.106, Ciawigebang, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Li Wasita",
                "email" => "suratsmanci@yahoo.com",
                "nohp" => "0231878326",
                "akreditasi" => "A",
                "guru" => 57,
                "siswa_laki" => 270,
                "siswa_perempuan" => 907,
                "kurikulum" => "SMA 2013 MIPA",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 24,
                "laboratorium" => 3,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212956,
                "user_id" => 9,
                "nama" => "SMA Negeri 2 Kuningan",
                "slug" => "smanegeri2kuningan",
                "status" => "Negeri",
                "latitude" => "108.4859667",
                "longitude" => "-6.978916364",
                "kecamatan" => "Kuningan",
                "alamat" => "Jl. Raya Siliwangi No.108, Ciawigebang, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Iman Nuryaman",
                "email" => "info@manciawigebang.sch.id",
                "nohp" => "0231878368",
                "akreditasi" => "A",
                "guru" => 63,
                "siswa_laki" => 407,
                "siswa_perempuan" => 697,
                "kurikulum" => "SMA 2013 Bhs&Budaya",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 31,
                "laboratorium" => 5,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212961,
                "user_id" => 10,
                "nama" => "SMA Negeri 1 Kuningan",
                "slug" => "smanegeri1kuningan",
                "status" => "Negeri",
                "latitude" => "108.4822064",
                "longitude" => "6.977575256",
                "kecamatan" => "Kuningan",
                "alamat" => "Jl. Siliwangi No.55, Purwawinangun, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Dedi Suardi",
                "email" => "smankuningan1@gmail.com",
                "nohp" => "0231871594",
                "akreditasi" => "A",
                "guru" => 61,
                "siswa_laki" => 442,
                "siswa_perempuan" => 707,
                "kurikulum" => "SMA 2013 MIPA",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 32,
                "laboratorium" => 4,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212955,
                "user_id" => 11,
                "nama" => "SMA Negeri 3 Kuningan",
                "slug" => "smanegeri3kuningan",
                "status" => "Negeri",
                "latitude" => "108.4843637",
                "longitude" => "-6.976478490",
                "kecamatan" => "Kuningan",
                "alamat" => "Jl. Siliwangi No.13, Kuningan, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Moch. Chaeri",
                "email" => "tu@sman3kuningan.sch.id",
                "nohp" => "02318900050",
                "akreditasi" => "A",
                "guru" => 49,
                "siswa_laki" => 410,
                "siswa_perempuan" => 649,
                "kurikulum" => "SMA 2013 MIPA",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 21,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20252161,
                "user_id" => 12,
                "nama" => "SMK Negeri 6 Kuningan",
                "slug" => "smknegeri6kuningan",
                "status" => "Negeri",
                "latitude" => "108.5002936",
                "longitude" => "-6.805958683",
                "kecamatan" => "Pancalang",
                "alamat" => "Jalan Raya, Sindangkempeng, Kec. Pancalang, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Rosnanti",
                "email" => "smkn6kuningan@yahoo.com",
                "nohp" => "02318910123",
                "akreditasi" => "A",
                "guru" => 57,
                "siswa_laki" => 841,
                "siswa_perempuan" => 392,
                "kurikulum" => "SMK 2013 Rev. Multimedia",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 21,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20246370,
                "user_id" => 13,
                "nama" => "SMK Negeri 5 Kuningan",
                "slug" => "smknegeri5kuningan",
                "status" => "Negeri",
                "latitude" => "108.5747448",
                "longitude" => "-6.963865152",
                "kecamatan" => "Ciawigebang",
                "alamat" => "Ciawilor, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Efendi",
                "email" => "smkn5_kng@yahoo.com",
                "nohp" => "0231878708",
                "akreditasi" => "A",
                "guru" => 87,
                "siswa_laki" => 1144,
                "siswa_perempuan" => 990,
                "kurikulum" => "SMK 2013 Rev. Teknik & Bisnis Sepeda Motor",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 34,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20279827,
                "user_id" => 14,
                "nama" => "SMK Negeri 1 Cilimus",
                "slug" => "smknegeri1cilimus",
                "status" => "Negeri",
                "latitude" => "108.5052217",
                "longitude" => "-6.861786515",
                "kecamatan" => "Cilimus",
                "alamat" => "Caracas, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Nono Sudrono",
                "email" => "smkn_1cilimus@yahoo.com ",
                "nohp" => "02318910145",
                "akreditasi" => "A",
                "guru" => 58,
                "siswa_laki" => 374,
                "siswa_perempuan" => 793,
                "kurikulum" => "SMK 2013 Rev. Usaha Perjalanan Wisata",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 20,
                "laboratorium" => 1,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212913,
                "user_id" => 15,
                "nama" => "SMK Negeri 1 Kuningan",
                "slug" => "smknegeri1kuningan",
                "status" => "Negeri",
                "latitude" => "108.4543026",
                "longitude" => "-6.977568455",
                "kecamatan" => "Cigugur",
                "alamat" => "Jl. Sukamulya No.1, Cigugur, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Didin Wahyudin",
                "email" => "smkn1_kng@yahoo.co.id",
                "nohp" => "0231871013",
                "akreditasi" => "A",
                "guru" => 85,
                "siswa_laki" => 1266,
                "siswa_perempuan" => 396,
                "kurikulum" => "SMK 2013 Rev. Produksi Grafika",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 54,
                "laboratorium" => 3,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212912,
                "user_id" => 16,
                "nama" => "SMK Negeri 2 Kuningan",
                "slug" => "smknegeri2kuningan",
                "status" => "Negeri",
                "latitude" => "108.4612640",
                "longitude" => "-6.979856504",
                "kecamatan" => "Cigugur",
                "alamat" => "Jl. Cigugur Sukamulya No.77, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Ibnu Udy Prasetyo",
                "email" => "info@smkn2kng.sch.id",
                "nohp" => "0231689112",
                "akreditasi" => "A",
                "guru" => 96,
                "siswa_laki" => 188,
                "siswa_perempuan" => 1713,
                "kurikulum" => "SMK 2013 Rev. Rekayasa Perangkat Lunak",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 51,
                "laboratorium" => 3,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20254698,
                "user_id" => 17,
                "nama" => "SMK Muhammadiyah 3 Kuningan",
                "slug" => "smkmuhammadiyah3kuningan",
                "status" => "Swasta",
                "latitude" => "108.4867236",
                "longitude" => "-6.922190233",
                "kecamatan" => "Jalaksana",
                "alamat" => "Jl. Raya Jalaksana No.188, Jalaksana, Kec. Jalaksana, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Lili Ruhyana",
                "email" => "smkmuh3kng@gmail.com",
                "nohp" => "02318910228",
                "akreditasi" => "B",
                "guru" => 13,
                "siswa_laki" => 71,
                "siswa_perempuan" => 29,
                "kurikulum" => "SMK 2013 Rev. Tkr Otomotif",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 5,
                "laboratorium" => 0,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212911,
                "user_id" => 18,
                "nama" => "SMK Negeri 3 Kuningan",
                "slug" => "smknegeri3kuningan",
                "status" => "Negeri",
                "latitude" => "108.4705874",
                "longitude" => "-6.951851695",
                "kecamatan" => "Cigugur",
                "alamat" => "Jl. Raya Cirendang, Cirendang, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Fuad",
                "email" => "uptd_smkn3kng@yahoo.co.id",
                "nohp" => "0231876833",
                "akreditasi" => "A",
                "guru" => 140,
                "siswa_laki" => 1883,
                "siswa_perempuan" => 677,
                "kurikulum" => "SMK 2013 Rev. Teknik Otomasi Industri",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 51,
                "laboratorium" => 4,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212920,
                "user_id" => 19,
                "nama" => "SMK PGRI Ciawigebang",
                "slug" => "smkpgriciawigebang",
                "status" => "Swasta",
                "latitude" => "108.5764783",
                "longitude" => "-6.971672900",
                "kecamatan" => "Ciawigebang",
                "alamat" => "Jl. Susukan  Ciawigebang, RT.01\/RW.01, Ciputat, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Sugiono",
                "email" => "smkpgriciawigebang@rocketmail.com",
                "nohp" => "0231878827",
                "akreditasi" => "A",
                "guru" => 39,
                "siswa_laki" => 482,
                "siswa_perempuan" => 258,
                "kurikulum" => "SMK 2013 Rev. Tkr Otomotif",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 43,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20268872,
                "user_id" => 20,
                "nama" => "SMK Negeri 1 Japara",
                "slug" => "smknegeri1japara",
                "status" => "Negeri",
                "latitude" => "108.5203906",
                "longitude" => "-6.896715217",
                "kecamatan" => "Japara",
                "alamat" => "Jl. Raya Puskesmas, Japara, Kec. Japara, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Asep Riyadi",
                "email" => "smkn1_japara@yahoo.co.id",
                "nohp" => "0231616363",
                "akreditasi" => "A",
                "guru" => 66,
                "siswa_laki" => 850,
                "siswa_perempuan" => 550,
                "kurikulum" => "SMK 2013 Rev. Teknik Otomasi Industri",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 19,
                "laboratorium" => 1,
                "isvalid" => "1",
                "perpustakaan" => 1
               ],
               [
                "id" => 20212918,
                "user_id" => 21,
                "nama" => "SMK Karya Nasional Kuningan",
                "slug" => "smkkaryanasionalkuningan",
                "status" => "Swasta",
                "latitude" => "108.4694136",
                "longitude" => "-6.954522296",
                "kecamatan" => "Kuningan",
                "alamat" => "Jl. Cirendang  Cigugur, Cirendang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek" => "Yepri Esa Trijaka",
                "email" => "smkkarnas40@gmail.com",
                "nohp" => "0231871404",
                "akreditasi" => "A",
                "guru" => 72,
                "siswa_laki" => 1669,
                "siswa_perempuan" => 323,
                "kurikulum" => "SMK 2013 Rev. Teknik Dan Bisnis Sepeda Motor",
                "penyelenggaraan" => "Sehari Penuh 5 Hari",
                "ruang_kelas" => 69,
                "laboratorium" => 2,
                "isvalid" => "1",
                "perpustakaan" => 1
               ]
    ];

        $this->db->table('sekolah')->insertBatch($sekolah);
    }
}
