<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class SekolahSeeder extends Seeder
{
    public function run()
    {
        $faker = \Faker\Factory::create('id_ID');

        // for ($i = 0; $i < 50; $i++) {
        //     $jenis = rand(0, 1) ? 'SMA' : 'SMK';
        //     $angka = mt_rand(1, 20);
        //     $kecamatan = $faker->city;
        //     $sekolah = $jenis . ' ' . $angka . ' ' . $kecamatan;
        //     $data = [
        //         'user_id' => $i + 2,
        //         'nama' => $sekolah,
        //         'slug' => url_title($sekolah, '-', true),
        //         'kecamatan' => $kecamatan,
        //         'alamat'    => $faker->address,
        //         'kepsek'    => $faker->userName,
        //         'email'    => $faker->safeEmail,
        //         'nohp'    => $faker->phoneNumber,
        //         'status'    => rand(0, 1) ? 'Negeri' : 'Swasta',
        //         'latitude'    => mt_rand(10823, 10847) / 100,
        //         'longitude'    => mt_rand(647, 712) / 100 * -1,
        //         'created_at'    => Time::createFromTimestamp($faker->unixTime),
        //         'updated_at'    => Time::now(),
        //     ];
        //     // Using Query Builder
        //     $this->db->table('sekolah')->insert($data);
        // }
        $sekolah = [
                [
                "id"=> 20212937,
                "user_id"=> 2,
                "nama"=> "SMA Negeri 1 Cilimus",
                "slug"=> "sma-negeri-1-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Cilimus, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Ade Saputra",
                "email"=> "smancilimus@yahoo.co.id",
                "nohp"=> "0231613076",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4983489",
                "longitude"=> "-6.874826233"
               ],
               [
                "id"=> 20212938,
                "user_id"=> 3,
                "nama"=> "SMA Negeri 1 Cigugur",
                "slug"=> "sma-negeri-1-cigugur",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Sukamulya No.12, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nono Sudarsono",
                "email"=> "sman1cggr@gmail.com",
                "nohp"=> "0231873840",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4626442",
                "longitude"=> "-6.983496516"
               ],
               [
                "id"=> 20212939,
                "user_id"=> 4,
                "nama"=> "SMA Negeri 1 Ciawigebang",
                "slug"=> "sma-negeri-1-ciawigebang",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Jl. Raya Siliwangi No.106, Ciawigebang, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Li Wasita",
                "email"=> "suratsmanci@yahoo.com",
                "nohp"=> "0231878326",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5888969",
                "longitude"=> "-6.974250955"
               ],
               [
                "id"=> 20212949,
                "user_id"=> 5,
                "nama"=> "SMA Negeri 1 Ciniru",
                "slug"=> "sma-negeri-1-ciniru",
                "kecamatan"=> "Ciniru",
                "alamat"=> "Ciniru, Kec. Ciniru, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dadan Sundana",
                "email"=> "smaciniru_kuningan@yahoo.co.id",
                "nohp"=> "081395568175",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4986768",
                "longitude"=> "-7.044542746"
               ],
               [
                "id"=> 20212950,
                "user_id"=> 6,
                "nama"=> "SMA Negeri 1 Ciwaru",
                "slug"=> "sma-negeri-1-ciwaru",
                "kecamatan"=> "Ciwaru",
                "alamat"=> "Jl. 11 April, Linggajaya, Kec. Ciwaru, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Achmad Darmanto",
                "email"=> "smanciwaru@gmail.com",
                "nohp"=> "0231890505",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.6409836",
                "longitude"=> "-7.085979269"
               ],
               [
                "id"=> 20212951,
                "user_id"=> 7,
                "nama"=> "SMA Negeri 1 Garawangi",
                "slug"=> "sma-negeri-1-garawangi",
                "kecamatan"=> "Garawangi",
                "alamat"=> "Jl. Raya Garawangi No.34, Karamatwangi, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Indra Gunawan Suryono",
                "email"=> "sma1garawangi@gmail.com",
                "nohp"=> "0231874244",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5420750",
                "longitude"=> "-6.999545722"
               ],
               [
                "id"=> 20212953,
                "user_id"=> 8,
                "nama"=> "SMA Negeri 1 Cidahu",
                "slug"=> "sma-negeri-1-cidahu",
                "kecamatan"=> "Cidahu",
                "alamat"=> "Jl. Kertawinangun No.09, Cidahu, Kec. Cidahu, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Isda Sugara",
                "email"=> "smansatucidahu@gmail.com",
                "nohp"=> "0231870212",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.64576945413944", 
                "longitude"=> "-6.980621808869963"
               ],
               [
                "id"=> 20212954,
                "user_id"=> 9,
                "nama"=> "SMA Negeri 1 Cibingbin",
                "slug"=> "sma-negeri-1-cibingbin",
                "kecamatan"=> "Cibingbin",
                "alamat"=> "Sukamaju, Cibingbin, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Sudarmoyo",
                "email"=> "sman1cibingbin@gmail.com",
                "nohp"=> "02318891615",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.7499676",
                "longitude"=> "-7.055336205"
               ],
               [
                "id"=> 20212955,
                "user_id"=> 10,
                "nama"=> "SMA Negeri 3 Kuningan",
                "slug"=> "sma-negeri-3-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Siliwangi No.13, Kuningan, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Moch. Chaeri",
                "email"=> "tu@sman3kuningan.sch.id",
                "nohp"=> "02318900050",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4843129",
                "longitude"=> "-6.976449210"
               ],
               [
                "id"=> 20212956,
                "user_id"=> 11,
                "nama"=> "SMA Negeri 2 Kuningan",
                "slug"=> "sma-negeri-2-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Aruji Kartawinata No.16, Kuningan, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Tri Suknaedi",
                "email"=> "sman2_kuningan@yahoo.co.id",
                "nohp"=> "0232871063",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4858916",
                "longitude"=> "-6.978916364"
               ],
               [
                "id"=> 20212957,
                "user_id"=> 12,
                "nama"=> "SMA Negeri 1 Subang",
                "slug"=> "sma-negeri-1-subang",
                "kecamatan"=> "Subang",
                "alamat"=> "Jl. H.O. Iskandar No.4, Subang, Kec. Subang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Wawan Muswana",
                "email"=> "smansubangkng@gmail.com",
                "nohp"=> "02316000159",
                "status"=> "Negeri", 
                "isvalid" => "1",
                "latitude"=> "108.52564841875409",
                "longitude"=> "-7.126124262731635"
               ],
               [
                "id"=> 20212958,
                "user_id"=> 13,
                "nama"=> "SMA Negeri 1 Mandirancan",
                "slug"=> "sma-negeri-1-mandirancan",
                "kecamatan"=> "Mandirancan",
                "alamat"=> "Jl. Siliwangi No.I A, Mandirancan, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Agus Hilman",
                "email"=> "sma1mandirancan@gmail.com",
                "nohp"=> "0231613026",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4730432",
                "longitude"=> "-6.815942422"
               ],
               [
                "id"=> 20212959,
                "user_id"=> 14,
                "nama"=> "SMA Negeri 1 Luragung",
                "slug"=> "sma-negeri-1-luragung",
                "kecamatan"=> "Luragung",
                "alamat"=> "Jl. Luragung, 45581, Cirahayu, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Suleha",
                "email"=> "sman1.luragung@yahoo.co.id",
                "nohp"=> "02318882020",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.6205720",
                "longitude"=> "-7.014006978"
               ],
               [
                "id"=> 20212960,
                "user_id"=> 15,
                "nama"=> "SMA Negeri 1 Lebakwangi",
                "slug"=> "sma-negeri-1-lebakwangi",
                "kecamatan"=> "Lebakwangi",
                "alamat"=> "Cinagara, Kec. Lebakwangi, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Moch. Chaeri",
                "email"=> "sman1_lebakwangi@yahoo.co.id",
                "nohp"=> "02318882382",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5857266",
                "longitude"=> "-7.027368337"
               ],
               [
                "id"=> 20212961,
                "user_id"=> 16,
                "nama"=> "SMA Negeri 1 Kuningan",
                "slug"=> "sma-negeri-1-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Siliwangi No.55, Purwawinangun, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dedi Suardi",
                "email"=> "smankuningan1@gmail.com",
                "nohp"=> "0231871594",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4821420",
                "longitude"=> "-6.977585906"
               ],
               [
                "id"=> 20212962,
                "user_id"=> 17,
                "nama"=> "SMAN 1 Kadugede",
                "slug"=> "sman-1-kadugede",
                "kecamatan"=> "Kadugede",
                "alamat"=> "Jl. Syech Manglayang No.65, Babatan, Kec. Kadugede, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Rhida Jaya Bhuana",
                "email"=> "smansaka@ymail.com",
                "nohp"=> "0231872816",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4507060",
                "longitude"=> "-7.004814904"
               ],
               [
                "id"=> 20212963,
                "user_id"=> 18,
                "nama"=> "SMA Negeri 1 Jalaksana",
                "slug"=> "sma-negeri-1-jalaksana",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Jl. Raya Padamenak, Jalaksana, 45554, Padamenak, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nanang Warsa",
                "email"=> "sman1jlksn.ops@gmail.com",
                "nohp"=> "0231874407",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4908686",
                "longitude"=> "-6.917629031"
               ],
               [
                "id"=> 20213305,
                "user_id"=> 19,
                "nama"=> "MAN 3 Kuningan",
                "slug"=> "man-3-kuningan",
                "kecamatan"=> "Luragung",
                "alamat"=> "Jl. Raya Luragung - Kuningan No.1, Cirahayu, Kec. Luragung, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Aripin",
                "email"=> "man_luragung01@yahoo.co.id",
                "nohp"=> "0231879995",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.6192143",
                "longitude"=> "-7.013423481"
               ],
               [
                "id"=> 20213306,
                "user_id"=> 20,
                "nama"=> "MAN 1 Kuningan",
                "slug"=> "man-1-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Mayasih No.881, Cigugur, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Winarto",
                "email"=> "info@man1kuningan.sch.id",
                "nohp"=> "0231873203",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4529344",
                "longitude"=> "-6.968616803"
               ],
               [
                "id"=> 20213307,
                "user_id"=> 21,
                "nama"=> "MAN 2 Kuningan",
                "slug"=> "man-2-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Raya Siliwangi No.108, Ciawigebang, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Iman Nuryaman",
                "email"=> "info@manciawigebang.sch.id",
                "nohp"=> "0231878368",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5904828",
                "longitude"=> "-6.974262808"
               ],
               [
                "id"=> 20246367,
                "user_id"=> 22,
                "nama"=> "SMA Negeri 1 Pasawahan",
                "slug"=> "sma-negeri-1-pasawahan",
                "kecamatan"=> "Pasawahan",
                "alamat"=> "Jl. Cirea-Pasawahan, Singkup, Kec. Pasawahan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Ipit Rahmiati",
                "email"=> "sman1pasawahan@gmail.com",
                "nohp"=> "02318306097",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.43435559646609", 
                "longitude"=> "-6.809425291471845"
               ],
               [
                "id"=> 20253827,
                "user_id"=> 23,
                "nama"=> "SMA Negeri 1 Darma",
                "slug"=> "sma-negeri-1-darma",
                "kecamatan"=> "Darma",
                "alamat"=> "Jl. Cipasung Desa, Cipasung, Kec. Darma, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dewi Asri Nirwana",
                "email"=> "sman_1darma@yahoo.com",
                "nohp"=> "082322586228",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.3928691",
                "longitude"=> "-7.017955919"
               ],
               [
                "id"=> 20212940,
                "user_id"=> 24,
                "nama"=> "SMA Pui Ciwedus Timbang",
                "slug"=> "sma-pui-ciwedus-timbang",
                "kecamatan"=> "Cigandamekar",
                "alamat"=> "Timbang, Kec. Cigandamekar, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dani Abdul Gani",
                "email"=> "smapuiciwedus9@gmail.com",
                "nohp"=> "0231614719",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5151258",
                "longitude"=> "-6.878428562"
               ],
               [
                "id"=> 20212941,
                "user_id"=> 25,
                "nama"=> "SMA PGRI Kuningan",
                "slug"=> "sma-pgri-kuningan",
                "kecamatan"=> "Purwaningrum",
                "alamat"=> "JL. Pramuka, No. 65 A, Kuningan, Jawa Barat",
                "kepsek"=> "Mega Seffiani",
                "email"=> "smapgrikuningan@gmail.com",
                "nohp"=> "0232871977",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5773146",
                "longitude"=> "-6.942346107"
               ],
               [
                "id"=> 20212942,
                "user_id"=> 26,
                "nama"=> "SMA Pertiwi Cilimus",
                "slug"=> "sma-pertiwi-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl. Raya Bandorasa No.25, RT.05\/RW.02, Bandorasa Wetan, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dede Rusnadi",
                "email"=> "smapeci@yahoo.co.id",
                "nohp"=> "0231613246",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4921943",
                "longitude"=> "-6.887786135"
               ],
               [
                "id"=> 20212943,
                "user_id"=> 27,
                "nama"=> "SMA Manbaul Ulum",
                "slug"=> "sma-manbaul-ulum",
                "kecamatan"=> "Pancalang",
                "alamat"=> "Jl. Parenca, Silebu, Pancalang, Kuningan Regency, West Java",
                "kepsek"=> "Aan Mutasian",
                "email"=> "sma_manbaul_ulum@yahoo.co.id",
                "nohp"=> "0231365512",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4977793",
                "longitude"=> "-6.836868682"
               ],
               [
                "id"=> 20212944,
                "user_id"=> 28,
                "nama"=> "SMA Kosgoro",
                "slug"=> "sma-kosgoro",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Aruji Kartawinata No.111, Kuningan, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Rizal Gunawan",
                "email"=> "smakoskng@yahoo.co.id",
                "nohp"=> "0231871992",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5026928",
                "longitude"=> "-6.966838919"
               ],
               [
                "id"=> 20212946,
                "user_id"=> 29,
                "nama"=> "SMA Islam Ainur Rafiq",
                "slug"=> "sma-islam-ainur-rafiq",
                "kecamatan"=> "Cigandamekar",
                "alamat"=> "Jl. Cigintung No.92, Panawuan, Kec. Cigandamekar, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Hamam",
                "email"=> "sma_ainurrafiq@yahoo.co.id",
                "nohp"=> "0231615096",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4959409",
                "longitude"=> "-6.880454408"
               ],
               [
                "id"=> 20213297,
                "user_id"=> 30,
                "nama"=> "MAS Nurul Falaah Jalaksana",
                "slug"=> "mas-nurul-falaah-jalaksana",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Gg. Harapan, Jalaksana, Kec. Jalaksana, Kabupaten Kuningan",
                "kepsek"=> "Dedeh Muztahidah",
                "email"=> "manurulfalah12@gmail.com",
                "nohp"=> "02318881328",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4870713",
                "longitude"=> "-6.926377184"
               ],
               [
                "id"=> 20213299,
                "user_id"=> 31,
                "nama"=> "MAS Miftahutholibin Timbang",
                "slug"=> "mas-miftahutholibin-timbang",
                "kecamatan"=> "Cigandamekar",
                "alamat"=> "Timbang, Cigandamekar, Timbang, Cigandamekar, Kuningan Regency, West Java",
                "kepsek"=> "Alal Jalaludin",
                "email"=> "emisdashboard@gmail.com",
                "nohp"=> "0231614712",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5151405",
                "longitude"=> "-6.880724806"
               ],
               [
                "id"=> 20213300,
                "user_id"=> 32,
                "nama"=> "MAS Ma'arif Kadugede",
                "slug"=> "mas-ma'arif-kadugede",
                "kecamatan"=> "Kadugede",
                "alamat"=> "Jl. Pesantren No. 80, Kadugede, Kec. Kadugede, Kab. Kuningan, Jawa Barat",
                "kepsek"=> "Iman Taofik",
                "email"=> "masmaarifkadugede@gmail.com",
                "nohp"=> "0231873845",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4830541",
                "longitude"=> "-6.981615354"
               ],
               [
                "id"=> 20213301,
                "user_id"=> 33,
                "nama"=> "MAS Pembangunan Mandirancan",
                "slug"=> "mas-pembangunan-mandirancan",
                "kecamatan"=> "Mandirancan",
                "alamat"=> "Jl. Siliwangi No.02, Dusun Pon, Kec. Mandirancan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Rudi Rahman",
                "email"=> "ma.pembangunan@yahoo.com",
                "nohp"=> "02318890838",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4839465",
                "longitude"=> "-6.967495488"
               ],
               [
                "id"=> 20213302,
                "user_id"=> 34,
                "nama"=> "MAS Maleber",
                "slug"=> "mas-maleber",
                "kecamatan"=> "Maleber",
                "alamat"=> "Jalan Raya Maleber No. 105 Dusun Puhun Rt 17 Rw 08",
                "kepsek"=> "Yayat Hayat Syamsiyah",
                "email"=> "spensamaleber@yahoo.co.id",
                "nohp"=> "085624440442",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> " 108.5697026",
                "longitude"=> "-7.027056285"
               ],
               [
                "id"=> 20213303,
                "user_id"=> 35,
                "nama"=> "MAS Husnul Khotimah",
                "slug"=> "mas-husnul-khotimah",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Raya Maniskidul No.199, Maniskidul, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Elfa Robi",
                "email"=> "infohusnulkhotimah@gmail.com",
                "nohp"=> "081324001600",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4890315",
                "longitude"=> "-6.910310029"
               ],
               [
                "id"=> 20213308,
                "user_id"=> 36,
                "nama"=> "MAS Al Mutawally",
                "slug"=> "mas-al-mutawally",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl. Pesantren No.177, Bojong, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Uud Syaprudin",
                "email"=> "mas-mutawally@gmail.com",
                "nohp"=> "0231615568",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4961230",
                "longitude"=> "-6.876110870"
               ],
               [
                "id"=> 20213309,
                "user_id"=> 37,
                "nama"=> "MAS Pui Cilimus",
                "slug"=> "mas-pui-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl. Haji Bakri, Cilimus, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nanan Chaerul Minan",
                "email"=> "saya_sairy@yahoo.com",
                "nohp"=> "0232613161",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5023998",
                "longitude"=> "-6.866495857"
               ],
               [
                "id"=> 20213310,
                "user_id"=> 38,
                "nama"=> "MAS Subulul Huda Darma",
                "slug"=> "mas-subulul-huda-darma",
                "kecamatan"=> "Darma",
                "alamat"=> "Jln. Raya Darma No. 214, Kawahmanuk, Kec. Darma, Kab. Kuningan Prov. Jawa Barat",
                "kepsek"=> "Otang Misbah",
                "email"=> "masubululhudadarma@yahoo.co.id",
                "nohp"=> "085316886566",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.3947470",
                "longitude"=> "-7.008214670"
               ],
               [
                "id"=> 20213324,
                "user_id"=> 39,
                "nama"=> "MAK Al Ihya Cigugur",
                "slug"=> "mak-al-ihya-cigugur",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Mayasih No.11, Cigugur, Puncak, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nurul Iman Hima Amrullah",
                "email"=> "alihyakuningan@gmail.com",
                "nohp"=> "0231873186",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4537570",
                "longitude"=> "-6.968626831"
               ],
               [
                "id"=> 20247295,
                "user_id"=> 40,
                "nama"=> "SMA Itus Jalaksana",
                "slug"=> "sma-itus-jalaksana",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Jalan Pajajaran No. 1A Desa Peusing Kecamatan Jalaksana Kabupaten Kuningan",
                "kepsek"=> "Nono Sodikin",
                "email"=> "smaitusjalaksana@gmail.com",
                "nohp"=> "02328617661",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4742599",
                "longitude"=> "-6.901455773"
               ],
               [
                "id"=> 20252882,
                "user_id"=> 41,
                "nama"=> "SMA Islam Terpadu Al-Multazam",
                "slug"=> "sma-islam-terpadu-al-multazam",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Linggarjati, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Edi Gunarto",
                "email"=> "smait@almultazam.sch.id",
                "nohp"=> "02318910022",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4675892",
                "longitude"=> "-6.880313415"
               ],
               [
                "id"=> 20268281,
                "user_id"=> 42,
                "nama"=> "MAS Al-Barokah",
                "slug"=> "mas-al-barokah",
                "kecamatan"=> "Kalimanggis",
                "alamat"=> "Kertawana, Kec. Kalimanggis, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Haris Hasyim Asyari",
                "email"=> "ma_al_barokah@yahoo.co.id",
                "nohp"=> "0231415106",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.6250080",
                "longitude"=> "-6.942990592"
               ],
               [
                "id"=> 20268282,
                "user_id"=> 43,
                "nama"=> "MAS Al-Maemun Sindangbarang",
                "slug"=> "mas-al-maemun-sindangbarang",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Jl. Raya Sindangbarang No. 25, Sindangbarang, Kec. Jalaksana, Kab. Kuningan Prov. Jawa Barat",
                "kepsek"=> "Dadang Suhendar",
                "email"=> "maemun_sindangbirang@gmail.com",
                "nohp"=> "081222621236",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5176296",
                "longitude"=> "-6.935145637"
               ],
               [
                "id"=> 20269281,
                "user_id"=> 44,
                "nama"=> "MAS Al-Amin",
                "slug"=> "mas-al-amin",
                "kecamatan"=> "Cibingbin",
                "alamat"=> "Sindangjawa, Cibingbin, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Aziz Sugiri",
                "email"=> "alamin_ypi@yahoo.com",
                "nohp"=> "082127140142",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.74681159646889", 
                "longitude"=> "-7.062895235234452"
               ],
               [
                "id"=> 20270923,
                "user_id"=> 45,
                "nama"=> "SMA Binaul Ummah",
                "slug"=> "sma-binaul-ummah",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Raya Cisantana, Cipari, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dian Nurdiaman",
                "email"=> "binaulummah@gmail.com",
                "nohp"=> "02318881441",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4674513",
                "longitude"=> "-6.963587750"
               ],
               [
                "id"=> 20276908,
                "user_id"=> 46,
                "nama"=> "MAS Plus Keterampilan Wadi Sofia",
                "slug"=> "mas-plus-keterampilan-wadi-sofia",
                "kecamatan"=> "Cidahu",
                "alamat"=> "Jl. Raya Cidahu - Ciledug, Cieurih, Kec. Cidahu, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Didi Rosadi",
                "email"=> "mas-wadia-sofia@gmail.com",
                "nohp"=> "0231878335",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.6514580",
                "longitude"=> "-6.975839009"
               ],
               [
                "id"=> 20277242,
                "user_id"=> 47,
                "nama"=> "MAS Nu As-Syukuriah",
                "slug"=> "mas-nu-as-syukuriah",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Jl. KH. Jaenudin Ciwelas Pangkalan, Pangkalan, Kec. Ciawigebang, Kab. Kuningan Prov. Jawa Barat",
                "kepsek"=> "Yopo Taufik Akbar",
                "email"=> "as-syukuriah@gmail.com",
                "nohp"=> "081324039095",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5665281",
                "longitude"=> "-6.964018052"
               ],
               [
                "id"=> 20281837,
                "user_id"=> 48,
                "nama"=> "MAS Bani Karim",
                "slug"=> "mas-bani-karim",
                "kecamatan"=> "Pancalang",
                "alamat"=> "Karangwangi, RT.01\/RW.03, Mekarjaya, Kec. Pancalang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Bahrudin",
                "email"=> "masbanikarim@yahoo.co.id",
                "nohp"=> "082129927405",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4850603",
                "longitude"=> "-6.976907698"
               ],
               [
                "id"=> 20282640,
                "user_id"=> 49,
                "nama"=> "MAS Al-Hidayah Sumbakeling",
                "slug"=> "mas-al-hidayah-sumbakeling",
                "kecamatan"=> "Pancalang",
                "alamat"=> "Sumbakeling, Kec. Pancalang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Maslahat",
                "email"=> "info@mtsalhidayahsumbakeling.sch.id",
                "nohp"=> "0232123456",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.49613465810897",
                "longitude"=> "-6.824357230194119"
               ],
               [
                "id"=> 20283760,
                "user_id"=> 50,
                "nama"=> "MAS Mishbahul Huda",
                "slug"=> "mas-mishbahul-huda",
                "kecamatan"=> "Kalimanggis",
                "alamat"=> "Dusun Puhun RT 013\/rW 003, -, Kec. Kalimanggis, Kab. Kuningan, Jawa Barat.",
                "kepsek"=> "Agus Pajar Budianto",
                "email"=> "mishbahul-huda@yahoo.co.id",
                "nohp"=> "0265791465",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.6210039",
                "longitude"=> "-6.963531599"
               ],
               [
                "id"=> 20283761,
                "user_id"=> 51,
                "nama"=> "MAS Daarul Quran",
                "slug"=> "mas-daarul-quran",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Jl. Pesantren, Cikubangmulya, Kec. Ciawigebang, Kab. Kuningan Prov. Jawa Barat",
                "kepsek"=> "Arif Hidayat",
                "email"=> "Andreyandri90@gmail.com",
                "nohp"=> "089675677955",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.6245670",
                "longitude"=> "-6.924064542"
               ],
               [
                "id"=> 20284467,
                "user_id"=> 52,
                "nama"=> "MAS Ashfanudin",
                "slug"=> "mas-ashfanudin",
                "kecamatan"=> "Kadugede",
                "alamat"=> "Dusun Manis RT\/RW 12\/03 Desa Windujanten Kec. Kadugede Kab. Kuningan",
                "kepsek"=> "Irfan Ahmad Harfan",
                "email"=> "mas-ashfanudin@yahoo.com",
                "nohp"=> "085388299153",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4584039",
                "longitude"=> "-6.992492577"
               ],
               [
                "id"=> 20284693,
                "user_id"=> 53,
                "nama"=> "MAS Daarul Huffaazh",
                "slug"=> "mas-daarul-huffaazh",
                "kecamatan"=> "Japara",
                "alamat"=> "Garatengah, Kec. Japara, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Jepi Rismayadi",
                "email"=> "masdulido@yahoo.co.id",
                "nohp"=> "085224080293",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4990772",
                "longitude"=> "-6.909367725"
               ],
               [
                "id"=> 20285052,
                "user_id"=> 54,
                "nama"=> "MAS Al-Ikhlash Jambar",
                "slug"=> "mas-al-ikhlash-jambar",
                "kecamatan"=> "Nusaherang",
                "alamat"=> "Jalan. Pesantren No. 05, Jl. Dusun Puhun No.Desa, Jambar, Kec. Nusaherang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Waridin",
                "email"=> "maalikhlasb@gmail.com.",
                "nohp"=> "081222914030",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4276863",
                "longitude"=> "-6.985857539"
               ],
               [
                "id"=> 20285370,
                "user_id"=> 55,
                "nama"=> "MAS Iibs El-Azam",
                "slug"=> "mas-iibs-el-azam",
                "kecamatan"=> "Pasawahan",
                "alamat"=> "Ciwiru, Kec. Pasawahan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Agus Abdul Karim",
                "email"=> "maiibselazam@gmail.com",
                "nohp"=> "081324495299",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4421306",
                "longitude"=> "-6.792027677"
               ],
               [
                "id"=> 20285940,
                "user_id"=> 56,
                "nama"=> "Madrasah Aliyah Plus Ar Ruhama",
                "slug"=> "madrasah-aliyah-plus-ar-ruhama",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl Raya Caracas - Sindanglaut (Sebelah Utara Lap. Sepakbola) Ds. Caracas Kec. Cilimus Kab. Kuningan",
                "kepsek"=> "Cucu Jubaedah",
                "email"=> "ar_ruhama@hotmail.com",
                "nohp"=> "0231619284",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5037181",
                "longitude"=> "-6.857039301"
               ],
               [
                "id"=> 20285941,
                "user_id"=> 57,
                "nama"=> "Madrasah Aliyah Nurul Falah Assubuki",
                "slug"=> "madrasah-aliyah-nurul-falah-assubuki",
                "kecamatan"=> "Maleber",
                "alamat"=> "RT.02, Parakan, Kec. Maleber, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Mokhamad Rofik Albana",
                "email"=> "man_assubuki@yahoo.com",
                "nohp"=> "081222018881",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5573528",
                "longitude"=> "-7.030838357"
               ],
               [
                "id"=> 20285948,
                "user_id"=> 58,
                "nama"=> "MAS Al-Muttaqien Manislor",
                "slug"=> "mas-al-muttaqien-manislor",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "RT 01 RW 01 dusun 1 desa, Manislor, Kec. Jalaksana, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Masrayah",
                "email"=> "mts.almuttaqien.bpp@gmail.com",
                "nohp"=> "085882991023",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4890739",
                "longitude"=> "-6.903379071"
               ],
               [
                "id"=> 20212911,
                "user_id"=> 59,
                "nama"=> "SMK Negeri 3 Kuningan",
                "slug"=> "smk-negeri-3-kuningan",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Raya Cirendang, Cirendang, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Fuad",
                "email"=> "uptd_smkn3kng@yahoo.co.id",
                "nohp"=> "0231876833",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4706089",
                "longitude"=> "-6.951798445"
               ],
               [
                "id"=> 20212912,
                "user_id"=> 60,
                "nama"=> "SMK Negeri 2 Kuningan",
                "slug"=> "smk-negeri-2-kuningan",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Cigugur Sukamulya No.77, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Ibnu Udy Prasetyo",
                "email"=> "info@smkn2-kng.sch.id",
                "nohp"=> "0231689112",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4612372",
                "longitude"=> "-6.979915075"
               ],
               [
                "id"=> 20212913,
                "user_id"=> 61,
                "nama"=> "SMK Negeri 1 Kuningan",
                "slug"=> "smk-negeri-1-kuningan",
                "kecamatan"=> "Cigugur",
                "alamat"=> "Jl. Sukamulya No.1, Cigugur, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Didin Wahyudin",
                "email"=> "smkn1_kng@yahoo.co.id",
                "nohp"=> "0231871013",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.4543026",
                "longitude"=> "-6.977621702"
               ],
               [
                "id"=> 20246369,
                "user_id"=> 62,
                "nama"=> "SMK Negeri 4 Kuningan",
                "slug"=> "smk-negeri-4-kuningan",
                "kecamatan"=> "Cidahu",
                "alamat"=> "Jl. Puter Sari Cikeusik No.73, Cikeusik, Kec. Cidahu, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Yayan Supyan",
                "email"=> "admin@smkn4kuningan.sch.id",
                "nohp"=> "082216958783",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> " 108.6841703",
                "longitude"=> "-6.955666447"
               ],
               [
                "id"=> 20246370,
                "user_id"=> 63,
                "nama"=> "SMK Negeri 5 Kuningan",
                "slug"=> "smk-negeri-5-kuningan",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Ciawilor, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Efendi",
                "email"=> "smkn5_kng@yahoo.com",
                "nohp"=> "0231878708",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5747341",
                "longitude"=> "-6.963939700"
               ],
               [
                "id"=> 20252161,
                "user_id"=> 64,
                "nama"=> "SMK Negeri 6 Kuningan",
                "slug"=> "smk-negeri-6-kuningan",
                "kecamatan"=> "Pancalang",
                "alamat"=> "Jalan Raya, Sindangkempeng, Kec. Pancalang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Rosnanti",
                "email"=> "smkn6kuningan@yahoo.com",
                "nohp"=> "02318910123",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5002828",
                "longitude"=> "-6.806065216"
               ],
               [
                "id"=> 20254692,
                "user_id"=> 65,
                "nama"=> "SMK Negeri 1 Luragung",
                "slug"=> "smk-negeri-1-luragung",
                "kecamatan"=> "Luragung",
                "alamat"=> "Jl. Raya Luragung-Cidahu, RT. 3 \/ RW. 3, Luragung, Luragunglandeuh, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Muhsin",
                "email"=> "smkn1luragung@gmail.com",
                "nohp"=> "0231879932",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.6415927",
                "longitude"=> "-7.012470923"
               ],
               [
                "id"=> 20268872,
                "user_id"=> 66,
                "nama"=> "SMK Negeri 1 Japara",
                "slug"=> "smk-negeri-1-japara",
                "kecamatan"=> "Japara",
                "alamat"=> "Jl. Raya Puskesmas, Japara, Kec. Japara, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Asep Riyadi",
                "email"=> "smkn1_japara@yahoo.co.id",
                "nohp"=> "0231616363",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5203799",
                "longitude"=> "-6.896725868"
               ],
               [
                "id"=> 20272450,
                "user_id"=> 67,
                "nama"=> "SMK Negeri 1 Cilimus",
                "slug"=> "smk-negeri-1-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Caracas, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nono Sudrono",
                "email"=> "smkn_1cilimus@yahoo.com",
                "nohp"=> "02318910145",
                "status"=> "Negeri",
                "isvalid" => "1",
                "latitude"=> "108.5052325",
                "longitude"=> "-6.861839775"
               ],
               [
                "id"=> 20212908,
                "user_id"=> 68,
                "nama"=> "SMK Pertiwi Kuningan",
                "slug"=> "smk-pertiwi-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Siliwangi No.26A, Kasturi, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dea Ariana Vamitrianto",
                "email"=> "smkpertiwikng@yahoo.com",
                "nohp"=> "0231875135",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4889957",
                "longitude"=> "-6.950459445"
               ],
               [
                "id"=> 20212909,
                "user_id"=> 69,
                "nama"=> "SMK Pertiwi Cilimus",
                "slug"=> "smk-pertiwi-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl. Raya Bandorasa No.25, RT.05\/RW.02, Bandorasa Wetan, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Totoh Miftahudin",
                "email"=> "smkpertiwiclms@gmail.com",
                "nohp"=> "02318611192",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4921943",
                "longitude"=> "-6.887860695"
               ],
               [
                "id"=> 20212914,
                "user_id"=> 70,
                "nama"=> "SMK Muhammadiyah 1 Kuningan",
                "slug"=> "smk-muhammadiyah-1-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. RE. Martadinata No.148 A, Ciporang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Maskam",
                "email"=> "smk_muhi_kng@yahoo.co.id",
                "nohp"=> "08588288301",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5006885",
                "longitude"=> "-6.952979314"
               ],
               [
                "id"=> 20212915,
                "user_id"=> 71,
                "nama"=> "SMK Muhammadiyah 2 Kuningan",
                "slug"=> "smk-muhammadiyah-2-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Raya Cigugur No.28, Kuningan, Kec. Kuningan, Kabupaten Kuningan",
                "kepsek"=> "Ridwan Hadisantoso",
                "email"=> "smkm2.kng@gmail.com",
                "nohp"=> "0231873475",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4681465",
                "longitude"=> "-6.958355739"
               ],
               [
                "id"=> 20212916,
                "user_id"=> 72,
                "nama"=> "SMK Model Patriot IV Ciawigebang",
                "slug"=> "smk-model-patriot-iv-ciawigebang",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Sidaraja, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Lip Sabit",
                "email"=> "smk_model_patriot75@yahoo.com",
                "nohp"=> "0231878977",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5709267",
                "longitude"=> "-6.980078556"
               ],
               [
                "id"=> 20212917,
                "user_id"=> 73,
                "nama"=> "SMK Korpri Kuningan",
                "slug"=> "smk-korpri-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. RE. Martadinata, Cijoho, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nana Mulyana",
                "email"=> "smkkorpri_68@yahoo.com",
                "nohp"=> "085624853247",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4948245",
                "longitude"=> "-6.970336451"
               ],
               [
                "id"=> 20212918,
                "user_id"=> 74,
                "nama"=> "SMK Karya Nasional",
                "slug"=> "smk-karya-nasional",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Cirendang - Cigugur, Cirendang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Yepri Esa Trijaka",
                "email"=> "smkkarnas40@gmail.com",
                "nohp"=> "0231871404",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4694672",
                "longitude"=> "-6.954522296"
               ],
               [
                "id"=> 20212919,
                "user_id"=> 75,
                "nama"=> "SMK Daya Mandiri",
                "slug"=> "smk-daya-mandiri",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Raya Cileuleuy, Cigugur, 45552, Puncak, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Didin Wahyudin",
                "email"=> "smkmandiri01@gmail.com",
                "nohp"=> "081911387383",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4336494",
                "longitude"=> "-6.965736352"
               ],
               [
                "id"=> 20212920,
                "user_id"=> 76,
                "nama"=> "SMK PGRI Ciawigebang",
                "slug"=> "smk-pgri-ciawigebang",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Jl. Susukan - Ciawigebang, RT.01\/RW.01, Ciputat, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Sugiono",
                "email"=> "smkpgriciawigebang@rocketmail.com",
                "nohp"=> "0231878827",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5764247",
                "longitude"=> "-6.971598354"
               ],
               [
                "id"=> 20212921,
                "user_id"=> 77,
                "nama"=> "SMK Swadaya Pui Cilimus",
                "slug"=> "smk-swadaya-pui-cilimus",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Jl. H. Bakri No.94, Caracas, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dadan Mukdana",
                "email"=> "smk.pui_kng@yahoo.com",
                "nohp"=> "02318910400",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5005358",
                "longitude"=> "-6.864632571"
               ],
               [
                "id"=> 20212922,
                "user_id"=> 78,
                "nama"=> "SMK Taruna Bhakti",
                "slug"=> "smk-taruna-bhakti",
                "kecamatan"=> "Kadugede",
                "alamat"=> "Jl. Veteran, Babatan, Kec. Kadugede, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Mohammad Iqbal",
                "email"=> "smktarunabhakti1999@gmail.com",
                "nohp"=> "08815229265",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4488885",
                "longitude"=> "-6.876032986"
               ],
               [
                "id"=> 20212934,
                "user_id"=> 79,
                "nama"=> "SMK Yamsik",
                "slug"=> "smk-yamsik",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Kuningan, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Iyas Suslia",
                "email"=> "smk.yamsik@gmail.com",
                "nohp"=> "0232879311",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4868816",
                "longitude"=> "-6.978643954"
               ],
               [
                "id"=> 20212935,
                "user_id"=> 80,
                "nama"=> "SMK Budi Bhakti",
                "slug"=> "smk-budi-bhakti",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Raya Cimalati Sukasari Mandirancan, Sukasari, Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Rijal Putra Pamungkas",
                "email"=> "smk_budibhakti@yahoo.co.id",
                "nohp"=> "02318890833",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4634980",
                "longitude"=> "-6.806902777"
               ],
               [
                "id"=> 20212936,
                "user_id"=> 81,
                "nama"=> "SMK Bm Yalti",
                "slug"=> "smk-bm-yalti",
                "kecamatan"=> "Cilimus",
                "alamat"=> "Linggarjati, Kec. Cilimus, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Slamet",
                "email"=> "smkyalti@yahoo.com",
                "nohp"=> "085864126610",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4759891",
                "longitude"=> "-6.878089662"
               ],
               [
                "id"=> 20212952,
                "user_id"=> 82,
                "nama"=> "SMK Bina Swasta",
                "slug"=> "smk-bina-swasta",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Pramuka No.67A, Purwawinangun, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Dadan Ramdani",
                "email"=> "smkbinaswasta_kng67a@yahoo.com",
                "nohp"=> "0231871198",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4786532",
                "longitude"=> "-6.976262361"
               ],
               [
                "id"=> 20229252,
                "user_id"=> 83,
                "nama"=> "SMK Auto Matsuda",
                "slug"=> "smk-auto-matsuda",
                "kecamatan"=> "Maleber",
                "alamat"=> "Jalan No.192, Kutaraja, Kec. Maleber, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Abdul Muhyi",
                "email"=> "smk.automatsuda@gmail.com",
                "nohp"=> "085961748111",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5626361",
                "longitude"=> "-7.017294857"
               ],
               [
                "id"=> 20229253,
                "user_id"=> 84,
                "nama"=> "SMK Darul Ulum",
                "slug"=> "smk-darul-ulum",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Eyang Hasan Maulani No.15, Karangtawang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Afif Saefulmillah",
                "email"=> "smkdarululum_kng@yahoo.com",
                "nohp"=> "0231873444",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5152572",
                "longitude"=> "-6.970758007"
               ],
               [
                "id"=> 20247269,
                "user_id"=> 85,
                "nama"=> "SMK Bakti Indonesia",
                "slug"=> "smk-bakti-indonesia",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Jl. Sadamantra, Babakanmulya, Kec. Jalaksana, Kabupaten Kuningan",
                "kepsek"=> "Muhamad Akcin",
                "email"=> "smk_bi_kng@yahoo.co.id",
                "nohp"=> "0231614061",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4871778",
                "longitude"=> "-6.915284534"
               ],
               [
                "id"=> 20252248,
                "user_id"=> 86,
                "nama"=> "SMK Al-Ihya Selajambe",
                "slug"=> "smk-al-ihya-selajambe",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Lapang Gintung No. 9 Selajambe, Selajambe, Kuningan, Jawa Barat",
                "kepsek"=> "Nurdin",
                "email"=> "admin@smkalihyaselajambe.sch.id",
                "nohp"=> "083824503567",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4593475",
                "longitude"=> "-7.118906596"
               ],
               [
                "id"=> 20254696,
                "user_id"=> 87,
                "nama"=> "SMK Bhakti Husada",
                "slug"=> "smk-bhakti-husada",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. Cigintung, Cirendang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Kemal Haris Rustama",
                "email"=> "smk.bhk3@gmail.com",
                "nohp"=> "02318881770",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4766283",
                "longitude"=> "-6.956133651"
               ],
               [
                "id"=> 20254697,
                "user_id"=> 88,
                "nama"=> "SMK Jagara",
                "slug"=> "smk-jagara",
                "kecamatan"=> "Kuningan",
                "alamat"=> "JL. Baru Jl. Lkr. Waduk Darma No.17, Jagara, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Beben Herwandi",
                "email"=> "smkjagarakng@gmail.com",
                "nohp"=> "02318882500",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4140480",
                "longitude"=> "-7.003844668"
               ],
               [
                "id"=> 20254698,
                "user_id"=> 89,
                "nama"=> "SMK Muhammadiyah 3 Kuningan",
                "slug"=> "smk-muhammadiyah-3-kuningan",
                "kecamatan"=> "Jalaksana",
                "alamat"=> "Jl. Raya Jalaksana No.188, Jalaksana, Kec. Jalaksana, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Lili Ruhyana",
                "email"=> "smkmuh3kng@gmail.com",
                "nohp"=> "02318910228",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5041187",
                "longitude"=> "-6.794399747"
               ],
               [
                "id"=> 20254699,
                "user_id"=> 90,
                "nama"=> "SMK Plus Pertiwi Sukamulya",
                "slug"=> "smk-plus-pertiwi-sukamulya",
                "kecamatan"=> "Cigugur",
                "alamat"=> "JL. Sukamulya - Bayuning, No. 240, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Mamat Rahman",
                "email"=> "pluspertiwi@gmail.com",
                "nohp"=> "0231876795",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4579449",
                "longitude"=> "-6.977566608"
               ],
               [
                "id"=> 20272449,
                "user_id"=> 91,
                "nama"=> "SMK Hidayatul Islam Garawangi",
                "slug"=> "smk-hidayatul-islam-garawangi",
                "kecamatan"=> "Garawangi",
                "alamat"=> "Citiusari, Kec. Garawangi, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "ACHMAD GUNANDI",
                "email"=> "smkhi.grw@gmail.com",
                "nohp"=> "081320679944",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> " 108.5387063",
                "longitude"=> "-6.993919212"
               ],
               [
                "id"=> 20272451,
                "user_id"=> 92,
                "nama"=> "SMK Taufiq Mubarok",
                "slug"=> "smk-taufiq-mubarok",
                "kecamatan"=> "Ciawigebang",
                "alamat"=> "Kapandayan, Kec. Ciawigebang, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Nana Mulyana Latief",
                "email"=> "smktaufiqmubarok@gmail.com",
                "nohp"=> "081394562008",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5758235",
                "longitude"=> "-6.975452154"
               ],
               [
                "id"=> 20274459,
                "user_id"=> 93,
                "nama"=> "SMK Teknologi Nasional Ar-Raswad",
                "slug"=> "smk-teknologi-nasional-ar-raswad",
                "kecamatan"=> "Japara",
                "alamat"=> "Jl. Dipati Ewangga, Cengal, Kec. Japara, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Diko Heryanto",
                "email"=> "smktenarjpr@yahoo.com",
                "nohp"=> "085324578989",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5508679",
                "longitude"=> "-6.916765930"
               ],
               [
                "id"=> 20281141,
                "user_id"=> 94,
                "nama"=> "SMK Gentra Pasundan Kuningan",
                "slug"=> "smk-gentra-pasundan-kuningan",
                "kecamatan"=> "Sindangagung",
                "alamat"=> "Tirtawangunan, Kec. Sindangagung, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Eman Suherman",
                "email"=> "smkgentrapasundan2014@gmail.com",
                "nohp"=> "081214436471",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5376306",
                "longitude"=> "-6.967620055"
               ],
               [
                "id"=> 20281154,
                "user_id"=> 95,
                "nama"=> "SMK Cendikia Utama",
                "slug"=> "smk-cendikia-utama",
                "kecamatan"=> "Lebakwangi",
                "alamat"=> "Langseb, Kec. Lebakwangi, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Muhana",
                "email"=> "smkcendikiautama@gmail.com",
                "nohp"=> "02318882532",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.5779308",
                "longitude"=> "-7.006818587"
               ],
               [
                "id"=> 20281809,
                "user_id"=> 96,
                "nama"=> "SMK Bina Nusantara Kuningan",
                "slug"=> "smk-bina-nusantara-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Jl. RE. Martadinata Kab. Kuningan",
                "kepsek"=> "Dadan Ramdani",
                "email"=> "nusantara.bina@gmail.com",
                "nohp"=> "085213237071",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4764999",
                "longitude"=> "-6.968801512"
               ],
               [
                "id"=> 20284350,
                "user_id"=> 97,
                "nama"=> "SMK Teknologi Manufaktur Indonesia Kuningan",
                "slug"=> "smk-teknologi-manufaktur-indonesia-kuningan",
                "kecamatan"=> "Kuningan",
                "alamat"=> "Purwawinangun, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Edi Sutejo",
                "email"=> "smk.tmin@gmail.com",
                "nohp"=> "02318902489",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.4778864",
                "longitude"=> "-6.975507606"
               ],
               [
                "id"=> 20284364,
                "user_id"=> 98,
                "nama"=> "SMK Persada Kuningan",
                "slug"=> "smk-persada-kuningan",
                "kecamatan"=> "Lebakwangi",
                "alamat"=> "Jl. Raya Luragung - Kuningan, Mekarwangi, Kec. Lebakwangi, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Arika Budiarka",
                "email"=> "persadakng01@yahoo.com",
                "nohp"=> "081213487601",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.6032285",
                "longitude"=> "-7.011506777"
               ],
               [
                "id"=> 20284673,
                "user_id"=> 99,
                "nama"=> "SMK Cibening",
                "slug"=> "smk-cibening",
                "kecamatan"=> "Cibening",
                "alamat"=> "Cibingbin, Kabupaten Kuningan, Jawa Barat",
                "kepsek"=> "Asep Hasanudin",
                "email"=> "surat.smkcibening@gmail.com",
                "nohp"=> "085659833985",
                "status"=> "Swasta",
                "isvalid" => "1",
                "latitude"=> "108.7658942",
                "longitude"=> "-7.059339164"
               ]
    ];

        $this->db->table('sekolah')->insertBatch($sekolah);
    }
}
